name: FTP Deploy (CodeIgniter 3)

on:
  push:
    branches:
      - main # deploy only when pushing to main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Deploy files via FTP (Explicit TLS)
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_HOST }} # 91.204.209.211
          username: ${{ secrets.FTP_USERNAME }} # edwin@edflix.fun
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftps
          security: explicit # this matches “Use explicit FTP over TLS”
          local-dir: ./ # root of your repo
          server-dir: /public_html/ # adjust if needed
          exclude: | # don’t deploy these
            **/.git*
            **/.github*
            application/cache/**
            application/logs/**
            application/config/development/**
          dry-run: false
          log-level: verbose # show detailed logs
          timeout: 60000 # 60s timeout in case of slow transfers
